version: "3.9"

services:
    database:
        image: postgres
        container_name: database_exercise_tracker
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=exercise_tracker
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: exercise_tracker
        restart: always
        ports: 
            - 8000:8000
            - 9229:9229 
        volumes: 
            - .:/usr/app
        links: 
            - database
        depends_on:
            - database



volumes:
    pgdata:
        driver: local